### ISSUE TITLE
Move from SnapCI to a new CI provider

### ISSUE THREAD

**Issue by akjones** [rabblerouser/rabblerouser-stream-client#1]
SnapCI is going away (https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/) and we need to keep automated builds going.

We need to choose a new tool and move the build for this repo to it.

Needs to be done by end of May at the latest.

**Comment by ineffyble** [comment]
It looks like this can be closed, as the repo is now set up with TravisCI

**Comment by camjackson** [comment]
Correct, thank you!
